<ul class="maintabmenu multipletabmenu">
    <li ><a href="/admin/partner/">Partneři</a></li>
    <li class="current"><a href="#">Přidat Partnera</a></li>
</ul>

<div class="content">
    <div class="contenttitle">
        <h2 class="form"><span>Základní info</span></h2>
    </div>

    <form class="stdform stdform2" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>

        <p>
            <label>Partner*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::textInput('title', array($partner,'title'), true)}
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Logo*<small>*.jpg, *.jpeg, *.png, *.gif<br/>Max. 5MB</small></label>
            <span class="field">
                <input type="file" name="logo" accept="image/*"/>
                {if isset($errors["logo"])}
                <label class="error">{echo join("<br/>", $errors["logo"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>WWW*</label>
            <span class="field">
                <input type="url" required name="web" class="width80" 
                       value="{echo isset($partner)? $partner->web: ""}"/>
                {if isset($errors["web"])}
                <label class="error">{echo join("<br/>", $errors["web"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Sekce</label>
            <span class="field">
                <select name="section" class="width80">
                    <option value="partners">Partneři</option>
                    <option value="apnea">Apnea</option>
                </select>
            </span>
        </p>
        <p>
            <label>Pořadí<small>Max. 99</small></label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::textInput('rank', array($partner,'rank',1))}
                {if isset($errors["rank"])}
                <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                {/if}
            </span>
        </p>

        <p class="stdformbutton">
            <input name="submitAddPartner" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>