<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Partneři</a></li>
    <li><a href="/admin/partner/add/">Přidat Partnera</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Partneři</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <td class="head0">Logo</td>
                <td class="head1">Název</td>
                <td class="head0">WWW</td>
                <td class="head1">Vytvořen</td>
                <td class="head0">Stav</td>
                <td class="head1">&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            {if !empty($partners)}
                {foreach $partner in $partners}
                    <tr>
                        <td class="center">
                            <a href="{echo $partner->getLogo()}" data-lightbox="partner_log_{echo $partner->getId()}">
                                <img src="{echo $partner->getLogo()}" alt="{echo $partner->getTitle()}" height="50px" />
                            </a>
                        </td>
                        <td>{echo $partner->getTitle()}</td>
                        <td>
                            <a href="{echo $partner->getWeb()}" target="_blank">{echo $partner->getWeb()}</a>
                        </td>
                        <td>{echo $partner->getCreated()}</td>
                        <td>
                            {if ($partner->active)}<span class="infoLabel infoLabelGreen">Aktivní</span>{/if}
                        </td>
                        <td>
                            <a href="/admin/partner/edit/{echo $partner->getId()}" class="btn btn3 btn_pencil" title="Upravit"></a>
                            <a href="/admin/partner/delete/{echo $partner->getId()}" class="btn btn3 btn_trash ajaxDelete" title="Smazat"></a>
                        </td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>