<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Analytics</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="grid_4">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Počet návštěvníků - realtime</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--grid_4-->

    <div class="grid_12">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Graf návštěv</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--grid_12-->

    <div class="clear"></div>

    <div class="grid_8">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Doba návštěv</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--grid_8-->

    <div class="grid_8 last">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Návštěvy podle dne</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--grid_8-->

    <div class="clear"></div>

    <div class="grid_8">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Stránky</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--grid_8-->

    <div class="grid_8 last">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Titulky stránek</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--grid_8-->

    <div class="clear"></div><br />

    <div class="grid_8">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Webové prohlížeče</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--grid_8-->

    <div class="grid_8 last">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Mapa návštěvníků</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--grid_8-->

    <div class="clear"></div><br />

    <div class="grid_8">
        <div class="widgetbox">
            <div class="title"><h2 class="chart"><span>Rozlišení obrazovky</span></h2></div>
            <div class="widgetcontent">

            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--grid_8-->

    <div class="clear"></div>
</div>