<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/news/">Novinky</a></li>
    <li><a href="/admin/news/add/">Přidat novinku</a></li>
    <li class="current"><a href="#">Upravit novinku</a></li>
</ul><!--maintabmenu-->

{if isset($news)}
<div class="content">
    <div class="widgetbox">
        {if !empty($concepts)}
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Koncepty</span></h2>
            </div><!--contenttitle-->
            <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                <colgroup>
                    <col class="con0" /> <col class="con1" />
                </colgroup>
                <thead>
                    <tr>
                        <td class="head0">Vytvořen</td>
                        <td class="head1">Poslední změna</td>
                        <td class="head0">&nbsp;</td>
                    </tr>
                </thead>
                {foreach $concept in $concepts}
                <tr>
                    <td>{echo $concept->getCreated()}</td>
                    <td>{echo $concept->getModified()}</td>
                    <td><a href="/admin/news/loadconcept/{echo $concept->getId()}" class="btn btn3 btn_pencil ajaxLoadConcept" title="Načíst concept"></a>
                        <a href="/admin/concept/delete/{echo $concept->getId()}" class="btn btn3 btn_trash ajaxDelete" title="Smazat concept"></a></td>
                </tr>
                {/foreach}
            </table>
        {/if}
        
        <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>Základní info</span></h2>
        </div><!--contenttitle-->

        <form class="stdform stdform2" method="post" action="#" >
            <input type="hidden" name="conceptid" id="conceptid" value="{echo isset($conceptid) ? $conceptId:0}" />
            <input type="hidden" name="concepttype" id="concepttype" value="2" />
            <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
            <p>
                <label>Název*</label>
                <span class="field">
                    {echo \Admin\Helper\FormPrinter::input('text', 'title', array($news,'title'), array('required'=>true))}
                    {if isset($errors["title"])}
                    <label class="error">{echo join("<br/>", $errors["title"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Pořadí<small>Max. 99</small></label>
                <span class="field">
                    {echo \Admin\Helper\FormPrinter::input('text', 'rank', array($news,'rank',1))}
                    {if isset($errors["rank"])}
                    <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Teaser*<small>Max. 750 znaků</small></label>
                <span class="field">
                    <textarea rows="20" name="shorttext" id="ckeditor2">{echo \Admin\Helper\FormPrinter::iset($news,'shortBody')}</textarea>
                    {if isset($errors["shortBody"])}
                    <label class="error">{echo join("<br/>", $errors["shortBody"])}</label>
                    {/if}
                    <br/>
                    <button id="clear-teaser">Smazat</button>
                    <button id="teaser-new-paragraph">Nový odstavec</button>
                    <button id="teaser-readmore-link">Přidat odkaz na celý článek</button>
                    <button id="teaser-to-text">Zkopírovat do Text</button>
                    <button id="teaser-link-to-gallery">Odkaz na galerii</button>
                    <button id="teaser-link-to-action">Odkaz na akci</button>
                    <button id="teaser-link-to-news">Odkaz na novinku</button>
                    <button id="teaser-link-to-content">Odkaz na stránku</button>
                </span>
            </p>
            <p>
                <label>Text*</label>
                <span class="field">
                    <textarea name="text" id="ckeditor">{echo \Admin\Helper\FormPrinter::iset($news,'body')}</textarea>
                    {if isset($errors["body"])}
                    <label class="error">{echo join("<br/>", $errors["body"])}</label>
                    {/if}
                    <br/>
                    <button id="clear-text">Smazat</button>
                    <button id="text-new-paragraph">Nový odstavec</button>
                    <button id="text-to-teaser">Zkopírovat do Teaser</button>
                    <button id="text-link-to-gallery">Odkaz na galerii</button>
                    <button id="text-link-to-action">Odkaz na akci</button>
                    <button id="text-link-to-news">Odkaz na novinku</button>
                    <button id="text-link-to-content">Odkaz na stránku</button>
                </span>
            </p>

            <br/>
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Systémové info</span></h2>
            </div><!--contenttitle-->
            <p>
                <label>Aktivní</label>
                <span class="field">
                    <select name="active" class="width80">
                        {if $news->active}
                        <option value="0">Neaktivní</option>
                        <option value="1" selected>Aktivní</option>
                        {/if}{else}
                        <option value="0" selected>Neaktivní</option>
                        <option value="1">Aktivní</option>
                        {/else}
                    </select>
                </span>
            </p>
            <p>
                <label>Schváleno</label>
                <span class="field">
                    <select name="approve" class="width80">
                        {foreach $type in \App\Model\NewsModel::getStates()}
                            {script $sel=""}
                            {if $type_i == $news->approved}
                                {script $sel="selected"}
                            {/if}
                        
                            <option value="{echo $type_i}" {echo $sel}>{echo $type}</option>
                        {/foreach}
                    </select>
                </span>
            </p>
            <p>
                <label>V archivu</label>
                <span class="field">
                    <select name="archive" class="width80">
                        {if $news->archive}
                        <option value="0">Ne</option>
                        <option value="1" selected>Ano</option>
                        {/if}{else}
                        <option value="0" selected>Ne</option>
                        <option value="1">Ano</option>
                        {/else}
                    </select>
                </span>
            </p>

            <br/>
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Metadata</span></h2>
            </div><!--contenttitle-->
            <p>
                <label>Meta-název</label>
                <span class="field">
                    {echo \Admin\Helper\FormPrinter::input('text', 'metatitle', array($news,'metaTitle'), array('placeholder'=>'Výchozí hodnota: stejná jako Název'))}
                    {if isset($errors["metaTitle"])}
                    <label class="error">{echo join("<br/>", $errors["metaTitle"])}</label>
                    {/if}
                </span>
            </p>
            <p>
                <label>Meta-popis</label>
                <span class="field">
                    <textarea rows="5" name="metadescription" class="width80" >{echo \Admin\Helper\FormPrinter::iset($news,'metaDescription')}</textarea>
                    {if isset($errors["metaDescription"])}
                    <label class="error">{echo join("<br/>", $errors["metaDescription"])}</label>
                    {/if}
                    <br/>
                </span>
            </p>
            <p>
                <label>Klíčová slova<small>Pro interní vyhledávač</small></label>
                <span class="field">
                    {echo \Admin\Helper\FormPrinter::input('text', 'keywords', array($news,'keywords'), array('placeholder'=>"Oddělovač: mezera"))}
                    {if isset($errors["keywords"])}
                    <label class="error">{echo join("<br/>", $errors["keywords"])}</label>
                    {/if}
                </span>
            </p>

            <p class="stdformbutton">
                <input name="submitEditNews" type="submit" value="Uložit" class="submit radius2" />
                <input name="submitPreviewNews" type="submit" value="Zobrazit náhled" class="submit radius2" />
            </p>
        </form>
    </div>

</div>
<br class="clear-all"/>
<div id="insert-photo-dialog"><p></p></div>
<script type="text/javascript" src="/public/js/custom/build/news.js"></script>
{/if}