<button id="text-to-teaser">Zkopírovat do Teaser</button>
<button id="clear-text">Smazat</button>
<button id="text-new-paragraph">Nový odstavec</button>
<button id="text-link-to-gallery">Odkaz na galerii</button>
<button id="text-link-to-action">Odkaz na akci</button>
<button id="text-link-to-report">Odkaz na reportáž</button>
<button id="text-link-to-news">Odkaz na novinku</button>
<button id="text-link-to-content">Odkaz na stránku</button>