{if !empty($imessages)}
    {foreach $message in $imessages}
        {if $message->getMessageType() == \Admin\Model\ImessageModel::TYPE_INFO}
        <div class="notification msginfo">
            <p>{echo $message->getBody()}</p>
        </div>
        {/if}{elseif $message->getMessageType() == \Admin\Model\ImessageModel::TYPE_WARNING}
        <div class="notification msgalert">
            <p>{echo $message->getBody()}</p>
        </div>
        {/elseif}{else}
        <div class="notification msgerror">
            <p>{echo $message->getBody()}</p>
        </div>
        {/else}
    {/foreach}
{/if}