<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/imessage/">Zprávy</a></li>
    <li><a href="/admin/imessage/add/">Nová Zpráva</a></li>
    <li class="current"><a href="#">Editovat Zprávu</a></li>
</ul>

{if isset($imessage)}
<div class="content">
    <form class="stdform stdform2" method="post" action="#">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />

        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Zpráva</span></h2>
        </div>
        <p>
            <label>Title*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::input('text', 'title', array($imessage,'title'), array('required'=>true))}
                {if isset($errors["title"])}
                <label class="error">
                    {echo join("<br/>", $errors["title"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Typ*</label>
            <span class="field">
                <select name="mtype" class="width80">
                    {foreach $type in \Admin\Model\ImessageModel::getTypes()}
                        {script $sel=""}
                        {if $type_i == $imessage->actionType}
                            {script $sel="selected"}
                        {/if}

                        <option value="{echo $type_i}" {echo $sel}>{echo $type}</option>
                    {/foreach}
                </select>
                {if isset($errors["messageType"])}
                <label class="error">
                    {echo join("<br/>", $errors["messageType"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Text*</label>
            <span class="field">
                <textarea rows="10" name="text" class="width80">{echo \Admin\Helper\FormPrinter::iset($imessage,'body')}</textarea>
                {if isset($errors["body"])}
                <label class="error">
                    {echo join("<br/>", $errors["body"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Zobrazovat od*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::input('text', 'dfrom', array($imessage,'displayFrom'), array('class'=>'width40 datepicker'))}
                {if isset($errors["displayFrom"])}
                <label class="error">
                    {echo join("<br/>", $errors["displayFrom"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Zobrazovat do*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::input('text', 'dto', array($imessage,'displayTo'), array('class'=>'width40 datepicker2'))}
                {if isset($errors["displayTo"])}
                <label class="error">
                    {echo join("<br/>", $errors["displayTo"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Aktivní</label>
            <span class="field">
                <select name="active" class="width80">
                    {if $imessage->active}
                    <option value="0">Neaktivní</option>
                    <option value="1" selected>Aktivní</option>
                    {/if}{else}
                    <option value="0" selected>Neaktivní</option>
                    <option value="1">Aktivní</option>
                    {/else}
                </select>
            </span>
        </p>

        <p class="stdformbutton">
            <input type="submit" name="submitEditImessage" value="Uložit" class="submit radius2"/>
        </p>
    </form>
</div>
{/if}