<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/user/">Uživatelé</a></li>
    <li><a href="/admin/user/add/">Nový uživatel</a></li>
    <li class="current"><a href="#">Editovat uživatele</a></li>
</ul>

{if isset($user)}
<div class="content">
    <form class="stdform stdform2" method="post" action="#">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />

        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Osobní údaje</span></h2>
        </div>
        <p>
            <label>Jméno*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::input('text', 'firstname', array($user,'firstname'), array('required'=>true))}
                {if isset($errors["firstname"])}
                <label class="error">
                    {echo join("<br/>", $errors["firstname"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Příjmení*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::input('text', 'lastname', array($user,'lastname'), array('required'=>true))}
                {if isset($errors["lastname"])}
                <label class="error">
                    {echo join("<br/>", $errors["lastname"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Telefon</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::input('tel', 'phone', array($user,'phoneNumber'))}
                {if isset($errors["phoneNumber"])}
                <label class="error">
                    {echo join("<br/>", $errors["phoneNumber"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Notifikace</label>
            <span class="field">
                <input type="checkbox" name="actionNotification" value="1" {if $user->getNewActionNotification}checked="checked"{/if}/>
                    <span>Chci dostávat emailové oznámení o nových akcích</span><br/>
                <input type="checkbox" name="reportNotification" value="1" {if $user->getNewReportNotification}checked="checked"{/if}/>
                    <span>Chci dostávat emailové oznámení o nových reportážích</span>
            </span>
        </p>
        
        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Přihlašovací údaje</span></h2>
        </div>
        <p>
            <label>Email*</label>
            <span class="field">
                {echo \Admin\Helper\FormPrinter::input('email', 'email', array($user,'email'), array('required'=>true))}
                {if isset($errors["email"])}
                <label class="error">
                    {echo join("<br/>", $errors["email"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Původní heslo</label>
            <span class="field">
                <input type="password" name="oldpass" class="width80" value="" placeholder="nepovinné (v případě, že nechcete měnit heslo)"/>
                {if isset($errors["oldpass"])}
                <label class="error">
                    {echo join("<br/>", $errors["oldpass"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Heslo</label>
            <span class="field">
                <input type="password" name="password" class="width80" value="" placeholder="nepovinné (v případě, že nechcete měnit heslo)"/>
                {if isset($errors["password"])}
                <label class="error">
                    {echo join("<br/>", $errors["password"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Potvrdit heslo</label>
            <span class="field">
                <input type="password" name="password2" class="width80" value="" placeholder="nepovinné (v případě, že nechcete měnit heslo)"/>
                {if isset($errors["password2"])}
                <label class="error">
                    {echo join("<br/>", $errors["password2"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Aktivní</label>
            <span class="field">
                <select name="active" class="width80">
                    {if $user->active == 1}
                    <option value="0">Neaktivní</option>
                    <option value="1" selected>Aktivní</option>
                    {/if}{else}
                    <option value="0" selected>Neaktivní</option>
                    <option value="1">Aktivní</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Zablokován</label>
            <span class="field">
                <select name="blocked" class="width80">
                    {if $user->blocked == 1}
                    <option value="0">Účet není zablokovaný</option>
                    <option value="1" selected>Zablokován</option>
                    {/if}{else}
                    <option value="0" selected>Účet není zablokovaný</option>
                    <option value="1">Zablokován</option>
                    {/else}
                </select>
            </span>
        </p>

        {if $isSuperAdmin}
        <p>
            <label>Role</label>
            <span class="field">
                <select name="role" class="width80">
                    {foreach $role in $roles}
                        {script $sel=""}
                        {if $role_i == $user->getRole()}
                            {script $sel="selected"}
                        {/if}

                        <option value="{echo $role_i}" {echo $sel}>{echo $role}</option>
                    {/foreach}
                </select>
                {if isset($errors["role"])}
                <label class="error">
                    {echo join("<br/>", $errors["role"])}
                </label>
                {/if}
            </span>
        </p>
        {/if}
        {elseif $isAdmin}
        <p>
            <label>Role</label>
            <span class="field">
                <select name="role" class="width80">
                    {if $user->role == "role_admin"}
                    <option value="role_member">Člen</option>
                    <option value="role_participant">Člen s přístupem do administrace</option>
                    <option value="role_admin" selected>Admin</option>
                    {/if}{elseif $user->role == "role_participant"}
                    <option value="role_member">Člen</option>
                    <option value="role_participant" selected>Člen s přístupem do administrace</option>
                    <option value="role_admin">Admin</option>
                    {/elseif}{else}
                    <option value="role_member" selected>Člen</option>
                    <option value="role_participant">Člen s přístupem do administrace</option>
                    <option value="role_admin">Admin</option>
                    {/else}
                </select>
                {if isset($errors["role"])}
                <label class="error">
                    {echo join("<br/>", $errors["role"])}
                </label>
                {/if}
            </span>
        </p>
        {/elseif}

        <p class="stdformbutton">
            <input type="submit" name="submitEditUser" value="Uložit" class="submit radius2"/>
        </p>
    </form>
</div>
{/if}