<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/user/">Uživatelé</a></li>
    <li><a href="/admin/user/add/">Nový uživatel</a></li>
    <li class="current"><a href="#">Nápověda</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Uživatelé</span></h2>
    </div><!--contenttitle-->

    <div class="tabs">
        <ul>
            <li><a href="#roles">Uživatelské role</a></li>
        </ul>

        <div id="roles">
            <h3>Uživatelské role</h3>
            <p>
            <ul>
                <li>Člen - nemá přístup do administrace, využití zatím jen v bazaru</li>
                <li>Člen s přístupem do administrace - může vytvářet akce, novinky, reportáže a galerie</li>
                <li>Admin - může schvalovat články, vytvářet a upravovat Obsah webu, vytvářet uživatele a vidí část systémových nastavení</li>
                <li>Super Admin - pouze jako systémový účet</li>
            </ul>
            </p><br/><br/>
            <h3>Přístup do administrace</h3>
            <p>
                Pokud chcete přidělit uživateli přístup do administrace stačí vytvořit nového uživatele s rolí Člen s přístupem do administrace 
                nebo tuto roli nastavit již registrovanému uživateli. Roli Admin bych již nikomu nepřiděloval.
            </p>
        </div>
        
    </div>
</div>