<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/email/send/">Email</a></li>
    <li class="current"><a href="#">Šablony</a></li>
    <li><a href="/admin/email/add/">Nová šablona</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Emailové šablony</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable" >
        <colgroup>
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <td class="head0">ID</td><td class="head1">Název</td>
                <td class="head0">Typ</td><td class="head1">Vytvořeno</td>
                <td class="head0">Stav</td><td class="head1">&nbsp;</td>
            </tr>
        </thead>
        <tbody>

            {if (!empty($emails))}
                {script $c = 1}
                {foreach $email in $emails}
                    <tr>
                        <td>{echo $c}</td>
                        <td>{echo $email->getTitle()}</td>
                        <td>{if $email->getType()==1}Běžná{/if}{else}Systémová{/else}</td>
                        <td>{echo $email->getCreated()}</td>
                        <td>
                            {if ($email->active)}<span class="infoLabel infoLabelGreen">Aktivní</span>{/if}
                        </td>

                        <td>
                            <a href="/admin/email/edit/{echo $email->id}" class="btn btn3 btn_pencil" title="Upravit"></a> 
                            <a href="/admin/email/delete/{echo $email->id}" class="btn btn3 btn_trash ajaxDelete" title="Smazat"></a>
                        </td>
                    </tr>
                    {script $c++}
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>