<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="/admin/system/">Hlavní</a></li>
    <li><a href="/admin/system/settings/">Nastavení</a></li>
    {if $isSuperAdmin}<li><a href="/admin/system/showadminlog/">Admin log</a></li>{/if}
</ul><!--maintabmenu-->
<div class="content">

    <div class="one_fourth">
        <div class="contenttitle"><h2 class="form"><span>Smazat cache</span></h2></div>
        <form class="stdform stdform2" method="post" action="/admin/system/clearcache/">
            <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
            <p class="stdformbutton">
                <input name="clearCache" type="submit" value="Smazat cache" class="submit radius2" />
            </p>
        </form>
    </div>
    <div class="one_fourth">
        <div class="contenttitle"><h2 class="form"><span>Zálohovat databázi</span></h2></div>
        <form class="stdform stdform2" method="post" action="/admin/system/createdatabasebackup/">
            <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
            <p class="stdformbutton">
                Spouštěno automaticky každý den v 2:30<br/>
                <input name="createBackup" type="submit" value="Vytvořit zálohu" class="submit radius2" />
            </p>
        </form>
    </div>
    <div class="one_fourth">
        <div class="contenttitle"><h2 class="form"><span>Aktualizovat sitemap.xml</span></h2></div>
        <form class="stdform stdform2" method="post" action="/admin/system/generateSitemap/">
            <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
            <p class="stdformbutton">
                Spouštěno automaticky každý den v 3:00<br/>
                <input name="generateSitemap" type="submit" value="Aktualizovat sitemap.xml" class="submit radius2" />
            </p>
        </form>
    </div>
  
</div><!--widgetcontent-->

<br class="clear-all" />