<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/system/">Hlavní</a></li>
    <li><a href="/admin/system/settings/">Nastavení</a></li>
    <li class="current"><a href="#">Admin log</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Admin log</span></h2>
    </div><!--contenttitle-->

    <table cellpadding="0" cellspacing="0" border="0" class="stdtable" >
        <colgroup>
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <th class="head0">Vytvořeno</th>
                <th class="head1">Uživatelské jméno</th>
                <th class="head0">Modul</th>
                <th class="head1">Kontroler</th>
                <th class="head0">Akce</th>
                <th class="head1">Stav</th>
                <th class="head0">Referer</th>
                <th class="head1">Parametry</th>
            </tr>
        </thead>
        <tbody>
            {if !empty($adminlog)}
            {foreach $logitem in $adminlog}
            <tr>
                <td>{echo $logitem->created}</td>
                <td>{echo $logitem->userId}</td>
                <td>{echo $logitem->module}</td>
                <td>{echo $logitem->controller}</td>
                <td>{echo $logitem->action}</td>
                <td>{echo $logitem->result}</td>
                <td>{echo $logitem->httpreferer}</td>
                <td>{echo $logitem->params}</td>
            </tr>
            {/foreach}
            {/if}
        </tbody>
    </table>
</div>