<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/gallery/">Galerie</a></li>
    <li><a href="/admin/gallery/add/">Nová Galerie</a></li>
    <li class="current"><a href="#">Detail Galerie</a></li>
    <li><a href="/admin/gallery/edit/{echo $gallery->id}">Editovat Galerii</a></li>
</ul><!--maintabmenu-->

{if isset($gallery)}
<div class="content">
    <div class="grid_4">
        <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>{echo $gallery->title}</span></h2>
        </div><!--contenttitle-->
        <div>
            Autor: {echo $gallery->userAlias}<br/>
            Vytvořeno: {echo $gallery->created}<br/>
            Popis galerie:
            <p class="collectiondetail_description">
                {echo $gallery->description}
            </p>
        </div>
    </div>
    <div class="grid_4">
        <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>Avatar</span></h2>
        </div><!--contenttitle-->
        <br/>
        <div>
            {if $gallery->getImgThumb() == ""}
                Zatím není nastavený žádný avatar galerie
            {/if}{else}
                <img src="{echo $gallery->getImgThumb()}" height="180px"/>
            {/else}
        </div>
    </div>
    <div class="grid_8">
        <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>Nahrát fotky<button class="stdbtn marginleft15" id="dropzoneProcess">Nahrát</button></span></h2>
        </div><!--contenttitle-->
        <form action="/admin/gallery/upload/" class="dropzone">
            <input type="hidden" name="MAX_FILE_SIZE" value="18000000"/>
            <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
            <input type="hidden" name="galleryid"  value="{echo $gallery->getId()}"/>
            <input type="hidden" name="submitUpload" value="Upload" />

            <div class="fallback">
                <input type="file" name="file" />
            </div>
        </form>
    </div>
    <div class="clear"></div>
    <hr/>
    <div class="grid_16 margintop10" id="tabs-1">
        {script $photos = $gallery->getPhotos()}
        {if !empty($photos)}
        <div style="overflow:hidden;">
            <ul class="imagelist">
                {foreach $photo in $photos}
                    {if $photo->active}
                        <li class="photoactive">
                    {/if}{else}
                        <li class="photoinactive">
                    {/else}
                        <a href="{echo $photo->imgMain}" data-lightbox="gallery" rel="lightbox">
                            <img src="{echo $photo->imgThumb}" alt="" height="120px" />
                        </a>
                        <span>
                            <a href="{echo $photo->imgMain}" class="view" title="Zobrazit" target="_blank"></a>
                            <a href="/admin/gallery/changephotostatus/{echo $photo->id}" class="activate" title="Aktivovat/Deaktivovat"></a>
                            <a href="/admin/gallery/deletephoto/{echo $photo->id}" class="delete" title="Smazat"></a>
                        </span>
                    </li>
                {/foreach}
            </ul>
        </div>
        {/if}{else}
        <div class="notification msginfo"><a class="close"></a><p>Žádné foto v galerii</p></div>
        {/else}
    </div>
</div>
{/if}

<script type="text/javascript" src="/public/js/plugins/dropzone.min.js"></script>
<script type="text/javascript" src="/public/js/custom/build/gallery.js"></script>