<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Maintenance</title>
        <!---CSS Files-->
        <link rel="stylesheet" href="/public/css/custom/errorStyle.min.css" />
    </head>
    <body lang="cs">
        <div class="content container_12">
            <h1 id="error-heading">Maintenance</h1>
            <p id="error-desc">Hi there, page is currently under maintenance. We will be back ASAP.</p>
        </div>
        
        <div class="footer container_12">
            <p class="grid_12">THCFrame Error Page</p>
        </div>

    </body>
</html>