<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/redirect/">Přesměrování</a></li>
    <li class="current"><a href="#">Přidat přesměrování</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Nové přesměrování</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <p>
            <label>Modul</label>
            <span class="field">
                <select class="width80" name="module">
                    {if !empty($modules)}
                        {foreach $module in $modules}
                            <option value="{echo strtolower($module)}">{echo $module}</option>
                        {/foreach}
                    {/if}
                </select>
            </span>
        </p>
        <p>
            <label>Z URL*</label>
            <span class="field">
                <input class="width80" type="text" name="fromurl" value="{echo isset($redirect)? $redirect->fromPath: ""}" />
                {if isset($errors["fromPath"])}
                <label class="error">{echo join("<br/>", $errors["fromPath"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Na URL*</label>
            <span class="field">
                <input class="width80" type="text" name="tourl" value="{echo isset($redirect)? $redirect->toPath: ""}" />
                {if isset($errors["toPath"])}
                <label class="error">{echo join("<br/>", $errors["toPath"])}</label>
                {/if}
            </span>
        </p>
       
        <p class="stdformbutton">
            <input name="submitAddRedirect" type="submit" value="Uložit" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
