<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Feedback</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Feedback</span></h2>
    </div><!--contenttitle-->

    <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <td class="head0">ID</td>
                <td class="head1">Uživatel</td>
                <td class="head0">Text</td>
                <td class="head1">Vytvořen</td>
            </tr>
        </thead>
        <tbody>
            {if !empty($feedbacks)}
                {foreach $feedback in $feedbacks}
                    <tr>
                        <td>{echo $feedback->getId()}</td>
                        <td>{echo $feedback->getUserAlias() != ''?$feedback->getUserAlias():'annonym'}</td>
                        <td>{echo $feedback->getMessage()}</td>
                        <td>{echo $feedback->getCreated()}</td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>